### ISSUE TITLE
Whether it will support popular shells such as zsh, fish, etc.

### ISSUE THREAD

**Issue by xxluozl** [gitbito/CLI#17]
Hi, I want to install bito cli on zsh, but it doesn't seem to be supported now, will it support some popular shells in the future, thanks!

**Comment by bitoandy** [comment]
Hi @xxluozl ,

Currently the installation script supports bash which is mentioned in "installing Bito CLI (recommended)" section.
We will be adding support so that you can install directly with a command on other shells also, in case bash is not available.

For now, you can refer to [Installing with Manual Binary Download](https://github.com/gitbito/CLI#installing-with-manual-binary-download-not-recommended) to install the binary manually and it should work as long as the location where you installed Bito CLI is included in PATH or by using complete path to Bito CLI.

**Comment by xxluozl** [comment]
Thank you, I will try it.
