### ISSUE TITLE
BitoCLI would not work on a brand new installation

### ISSUE THREAD

**Issue by sharpe5** [gitbito/CLI#25]
Installed BitoCLI on Windows. Opened a brand new dos prompt, typed "bito". Nothing found. A "where bito" did not find anything.

Uninstalled, then reinstalled. This time, when I opened a brand new dos prompt, bito worked, and "where bito" showed "C:\Program Files (x86)\Bito\bito.exe".

Suggest updating BitoCLI so it does not require Admin privileges to install. If it requires Admin privileges, you are excluding most corporate clients as few devs have Admin access in an enterprise setting.

Suggest trying BitoCLI on a brand new Windows install, and working out why it fails the very first time. Perhaps spin up a brand new virtual machine and try a first-time installation?

**Comment by macky3099** [comment]
Hi @sharpe5,
Thank you for addressing and posting this issue. We will check more on this on our side and upate accordingly. 

Can you please let us know on which Windows version did you find this issue, Windows 10 or 11?

**Comment by macky3099** [comment]
Hi @sharpe5, with the new update of Bito CLI Version 3.5, the windows installer has been fixed to work without admin privileges as well. 

You can check it once and report back to us if you still face any issues.

Note: The new installer might still ask you to run with admin privileges during the first run, this is because it uninstalls the previous versions of Bito CLI if found which was installed via the admin privileges during the process.

**Comment by macky3099** [comment]
Hi @sharpe5, we are closing this issue for now, please feel free to reopen it if you face any issues. Thanks!
