### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by SimonJackler** [gitbito/CLI#44]
The purpose of Github is to distribute code, not binaries, right?

Why is the binary more than 11 MB? Is it not just a frontend for a http client that uses the Binto API? How can it then be so big? What more does it contain and do?

**Comment by macky3099** [comment]
Hi @SimonJackler,

Thanks for installing Bito CLI and reaching out to us.

For the queries you had mentioned, we would like to highlight the below points with respect to Bito CLI:

1. As of now we have not made our source code is not public, but we use GitHub for distribution of CLI binaries and at the same time it also helps us with tracking customer issues.
2. You might find that the size of Bito CLI is large, but this is because we use various libraries to help us achieve the core features of Bito CLI such as multiline input, handling the CLI configuration, encryption/decryption, authorization/authentication, various language support and a lot more. The size of Bito CLI can be optimized further but as of now we are focused on adding more functionality based on what the users have requested and gaps we have identified over the time.
3. Bito CLI also supports functionality for handling the context, parsing the output with proper format where required, required logging on local machine, supporting various languages in response output as well as during the user input for automating tasks via Bito CLI specific -p and -f options.
